'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../component/Navbar";
import Fotter from "../component/Fotter";
import "./globals.css";
import { usePathname } from "next/navigation";
import React, { useState, useEffect } from 'react'; // Import useState and useEffect

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata should be exported statically if possible, or removed from client components
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const [isClient, setIsClient] = useState(false);

  // This effect runs only on the client side, after the component has mounted.
  useEffect(() => {
    setIsClient(true);
  }, []);

  // Hide layout on these paths
  const hideLayout =
    pathname.startsWith("/auth") ||
    pathname === "/signin" ||
    pathname === "/signup" ||
    pathname === "/choose-role" ||
    pathname === "/registration" ||
    pathname === "/create-event" ||
    pathname === "/update-profile" ||
    pathname === "/design" ||
    pathname.startsWith("/dashboard");

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* By checking isClient, we ensure this conditional logic only runs on the client, preventing the hydration error. */}
        {isClient && !hideLayout && <Navbar />}
        {children}
        {isClient && !hideLayout && <Fotter />}
      </body>
    </html>
  );
}
